# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondetails',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotiondetails',
            name='items_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotiondetails',
            name='items_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotiondetails',
            name='items_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotiondetails',
            name='promotion',
            field=models.ForeignKey(default=1588, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_id', to='vendorInterface.Promotion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotiondetails',
            name='sales_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
