# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorInterface', '0002_auto_20170913_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiondetails',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='vendorInterface.Promotion'),
        ),
    ]
