# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorInterface', '0003_auto_20170913_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='numberOfPromotion',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
